### ISSUE TITLE
Use GetPrimitiveArrayCritical to avoid mallocs

### ISSUE THREAD

**Issue by jpountz** [decster/jnicompressions#2]
The JNI code always performs copies of the Java arrays in order to compress them. These copies could be avoided on some JVMs by using GetPrimitiveArrayCritical instead.

**Comment by decster** [comment]
I think I tried sun-java6 and it still make copies. I think GetPrimitiveArrayCritical can be used for input buffer. The output buffer still better using malloc, so as to skip one useless memcpy.

**Comment by jpountz** [comment]
I just looked at snappy-java to see whether and how it uses GetPrimitiveArrayCritical: http://code.google.com/p/snappy-java/source/browse/src/main/java/org/xerial/snappy/SnappyNative.cpp

Looks like it uses it for the input and the output so that there is no malloc and memcpy at all in case the JVM supports GetPrimitiveArrayCritical.

**Comment by decster** [comment]
I mean GetPrimitiveArrayCritical will do an extra memcpy, if GetPrimitiveArrayCritical() is not truly supported by JVM, it will alloc a new buffer and memcpy the content of dest buffer to the allocated temp buffer(which is useless, cause its output buffer and will be overwritten), using just malloc will save the memcpy. Consider sun(oracle) jdk is most popular jdk, and it seems not support GetPrimitiveArrayCritical(), using malloc seems a better solution in output buffer.

**Comment by jpountz** [comment]
Surprising, I thought it would be supported by most (if not all) Oracle JVMs, especially given that they have changes in Hotspot to use this function to reduce the number of memcy. http://hg.openjdk.java.net/jdk7/tl/jdk/rev/96d78263fdf7

**Comment by jpountz** [comment]
Sorry, the link I wanted to paste is http://hg.openjdk.java.net/jdk7/l10n/jdk/raw-rev/59f43e232481

**Comment by decster** [comment]
Thanks for the link, I'll make the change and get test results first.

**Comment by decster** [comment]
I changed to GetPrimitiveArrayCritical, and it works great, thanks for your advice:)

**Comment by jpountz** [comment]
Cool! How did this change impact test results? Is there any noticeable speedup?

**Comment by decster** [comment]
I already updated the test results in README, now it's the same speed as DirectBuffer.
